##################################################
#
#  MICROBE ANALYSIS
# * This script takes in CZ ID microbe reports, performs background correction
#   and then applies the rules-based-model for detection of pathogens.
# * It is also entrenched in code associated with project-specific analyses
#   including analysis of pathogen microbial mass, etc.
# 
#################################################

setwd("~/Downloads/plasma_classifiers/pathogen_rbm")
source("~/Downloads/plasma_classifiers/pathogen_rbm/idseqr/R/idseqr.R") # from https://github.com/czbiohub/idseqr
library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(dplyr)

# function to get maximum drop-off from a single sample (identify the outliers)
get_difs <- function(l){
  difs <- list()
  for(i in seq_along(l[1:length(l)-1])){
    difs[[i]] <- l[i] - l[i+1]
  }
  return(unlist(difs))
}

# function to apply the RBM
apply_rbm <- function(df, overview, id, plot_results = TRUE, output_directory = paste(outdir,"/rbm/",sep=''), colormode = FALSE){
  values <- df                            # DON'T APPLY THE LOG-TRANSFORMATION
  values <- sort(values[,id][!is.na(values[,id])], decreasing = TRUE)
  if(length(values) > 15){
    values <-  values[1:15]                   # restrict analysis to the top 15 organisms   
  }
  x <- get_difs(values)                       # identify the index of the maximum drop-off in RPM values
  if(length(x) == 0){
    top_orgs <- values
  }else{
    top_orgs <- values[1:which.max(x)]
  }
  
  # plot the results for visual interrogation
  if(plot_results){
    pdf(paste(output_directory, "RBM_",colnames(values)[id],".pdf", sep=""), height = 6, width = 6)
    par(mar = c(2, 10, 2, 2) + 0.2)
    title = paste(colnames(values)[id], overview[overview$sample_name == colnames(values)[id],c("initial_input_mass_ng")])
    barplot(values, las=2, horiz=TRUE, main = title, 
            col= c(rep("brown1",length(top_orgs)), rep("deepskyblue2", length(values)-length(top_orgs))), cex.names = .6, cex.main = .6)#, xlim=c(0,5))
    dev.off()
  }
  if(colormode){
    return(c(rep("brown1",length(top_orgs)), rep("deepskyblue2", length(values)-length(top_orgs))))
  }
  return(top_orgs)
}

run_microbe_analysis <- function(outdir){
  
  ##
  ## read in the microbe data and sample qc metrics
  ##
  getwd()
  
  # read in microbe data and overview statistics
  # require species-level hits, NT aln_len > 50
  microbe_reports <- read_microbe_reports('./data/microbe/earliplasma_dna_novaseq_01-2020_785/', tax_level=1, min_nt_alignment_length=50, min_nr_alignment_length=0)
  overview <- read.csv("./data/microbe/earlieplasma_dna_novaseq_01-2020_785_overview.csv")
  samplenames <- unique(microbe_reports$sample_name)
  
  # compute the total input mass based on ERCCs [extra information to provide with outputs]
  # formula: total mass / ercc mass = total reads / ercc reads
  total_input_mass <- ((overview$total_reads * overview$compression_ratio) / overview$total_ercc_reads) * 25
  initial_input_mass <- total_input_mass - 25   
  overview$initial_input_mass_ng <- initial_input_mass/1000
  
  # microbial mass as proportion of total input sample mass
  overview$microbial_mass <- overview$initial_input_mass_ng * (overview$nonhost_reads / overview$total_reads) 
  
  ## Doing the SPECIES:GENUS collapse here.
  microbe_reports %>%
    dplyr::filter(genus_tax_id > 0) %>%           # require genus taxid (removes "uncultured bacteria")
    dplyr::filter(nr_count > 0) %>%               # filter out taxons with 0 NR reads
    group_by(sample_name,genus_tax_id) %>%           # group by genus, select the top species within the genus 
    top_n(n=1, wt=nt_rpm) %>% 
    as.data.frame() -> microbe_reports_sp2genus
  microbe_reports <- microbe_reports_sp2genus
  microbe_reports_full <- microbe_reports
  
  
  ##
  ## Perform background correction using the function generated by Jack Kamm (https://github.com/czbiohub/idseqr)
  ##
  
  water_controls <- as.character(overview[overview$sample_type %in% c("H2Oextraction"),c("sample_name")])
  microbe_reports_bgc <- filter_background(microbe_reports, water_controls)
  microbe_reports_bgc$p_adj <- p.adjust(microbe_reports_bgc$p_val, "fdr")              ## apply multiple test correction (fdr = Benjamini & Hochberg)
  PVALUE <- 0.01
  sig_microbe_reports_bgc <- microbe_reports_bgc[microbe_reports_bgc$p_adj < PVALUE,]  
  microbe_reports <- sig_microbe_reports_bgc  
  write.csv(microbe_reports, paste(outdir,"all_bgc_taxa.csv", sep=''))
  
  ## DATA VISUALIZATION BEFORE DECIDING HOW TO DO THIS ALGORITHM
  metadata <- read.csv("./data/EARLI data merged_clinical missing solved_past medical_Chaz composite_virusesPresent_MTA_10-14-2020.csv", sep=",", stringsAsFactors = FALSE)
  metadata_full_for_roc <- metadata
  metadata <- metadata[,c("MICROBE_Plasma_DNA.Seq_filename", "EARLIStudyId","Barcode","Group","Blood","Lungs","Urine","Stool","Other")]
  metadata$ID <- unlist(lapply(metadata$Barcode, function(x){return(paste("EARLI_",x,sep=""))}))
  metadata$sample_name = metadata$MICROBE_Plasma_DNA.Seq_filename
  meta_overview <- merge(overview, metadata, all.x = TRUE, by="sample_name")
  colors <- c("brown1","orange","green","deepskyblue2","purple","pink")
  
  # for water samples, update sample name 
  meta_overview[meta_overview$sample_type %in% c("H2Oextraction", "H2Olibcontrol"),c("MICROBE_Plasma_DNA_Seq_filename")] <- meta_overview[meta_overview$sample_type %in% c("H2Oextraction", "H2Olibcontrol"),c("sample_name")]
  meta_overview$FullGroup <- apply(meta_overview, 1, function(x){if(x["sample_type"] %in% c("H2Oextraction", "H2Olibcontrol")){return("water")}else{return(x["Group"])}})
  meta_overview <- meta_overview[!is.na(meta_overview$FullGroup),]
  meta_overview <- meta_overview[order(meta_overview$initial_input_mass_ng),]
  
  mass_evaluation_df <- meta_overview[,c("FullGroup","initial_input_mass_ng","microbial_mass")]
  mass_evaluation_df$log_input_mass <- log10(mass_evaluation_df$initial_input_mass_ng)
  mass_evaluation_df$log_microbial_mass <- log10(mass_evaluation_df$microbial_mass)
  mass_evaluation_df$FullGroup <- as.factor(mass_evaluation_df$FullGroup)
  
  total_mass_threshold <- max(meta_overview[meta_overview$FullGroup == "water", c("initial_input_mass_ng")])   #threshold for total mass
  microbial_mass_threshold <- 0
  
  INCLUDE_LIST <- read.csv("./reference/1_Priority_pathogen_include_EARLI.csv", header = FALSE) # tbd what to do
  
  meta_overview <- meta_overview[order(meta_overview$FullGroup),]
  result_metrics <- list()
  pdf("~/Downloads/microbe_results.pdf", width=5, height=5)
  sig_microbe_reports_bgc_subset <- microbe_reports[microbe_reports$sample_name %in% meta_overview$sample_name, ]
  par(mar=c(1,1,1,1))
  
  sample_names <- intersect(meta_overview$sample_name, unique(sig_microbe_reports_bgc_subset$sample_name)) #meta_overview$sample_name
  
  for(SN in sample_names){
    print(SN)
    barcode <- meta_overview[meta_overview$sample_name==SN,c("ID")]
    print("barcode")
    print(barcode)
    
    this_report <- sig_microbe_reports_bgc_subset[sig_microbe_reports_bgc_subset$sample_name == SN,]
    this_report <- this_report[this_report$category != "viruses",]  ### REMOVE VIRUSES SINCE THIS  IS DNA AND  THEY THROW OFF THE CLUSTERING
    
    mass <- meta_overview[meta_overview$sample_name == SN, "initial_input_mass_ng"]
    microbe_mass <- meta_overview[meta_overview$sample_name == SN, "microbial_mass"]
    md <- meta_overview[meta_overview$sample_name == SN,]
    organism <- md[complete.cases(md[,c("sample_name")]),"Blood"]
    all_organisms <- paste("Blood: ", md[complete.cases(md[,c("sample_name")]),"Blood"], 
                           "\nLungs: ",  md[complete.cases(md[,c("sample_name")]),"Lungs"],
                           "\nUrine: ",  md[complete.cases(md[,c("sample_name")]),"Urine"],
                           "\nStool: ",  md[complete.cases(md[,c("sample_name")]),"Stool"],
                           "\nOther: ",  md[complete.cases(md[,c("sample_name")]),"Other"])
    blood_known_organisms <- unlist(md[complete.cases(md[,c("sample_name")]),c("Blood")])
    all_known_organisms_list <- unlist(md[complete.cases(md[,c("sample_name")]),c("Blood", "Lungs","Urine","Stool","Other")])
    group <-md[complete.cases(md[,c("sample_name")]),"FullGroup"]
    
    this_report %>%
      dplyr::filter(genus_tax_id > 0) %>%  # require genus taxid (removes "uncultured bacteria")
      dplyr::filter(nr_count > 0) %>%      # filter out taxons with 0 NR reads
      group_by(tax_id) %>%
      top_n(1, abs(nt_rpm)) %>% 
      as.data.frame() -> filtered_report
    
    sample1_subset <- filtered_report[,c("sample_name","tax_id","tax_level","name","nt_rpm","p_val", "nt_count")]
    sample1_subset$genus_name <- unlist(lapply(sample1_subset$name, function(x){return(strsplit(x,' ')[[1]][1])}))
    sample1_subset <- head(sample1_subset[order(sample1_subset$nt_rpm, decreasing=TRUE),],15)
    
    if(dim(filtered_report)[1] > 0){
      mat <- acast(filtered_report, name~sample_name, value.var="nt_rpm")
      
      result <- apply_rbm(mat, overview, 1, plot_results = FALSE, colormode = TRUE)
      print(result)
      
      text_color = "black"
      call_was_attempted <- TRUE
      if(microbe_mass < microbial_mass_threshold){
        text_color = "grey"
        call_was_attempted <- FALSE
      }
      
      # document which pathogens were called
      called_pathogens <- sample1_subset[result=="brown1",]
      called_pathogens <- called_pathogens[called_pathogens$nt_rpm > 1,] ## APPLY THRESHOLD FOR RPM > 1
      called_pathogens_significant <- called_pathogens[called_pathogens$p_val < PVALUE]
      called_pathogens_significant_species <- called_pathogens_significant$name
      called_pathogens_significant_genus <- unlist(lapply(called_pathogens_significant_species, function(x){return(strsplit(x,' ')[[1]][1])}))
      
      # we are applying the include list no matter what:
      apply_include_list <- TRUE
      if(apply_include_list){
        overlap_with_include_list <- c(intersect(called_pathogens_significant_genus, INCLUDE_LIST$V1), intersect(called_pathogens_significant_species, INCLUDE_LIST$V1))
        
        # if there are no INCLUDE LIST pathogens, then don't make a call bc there was such little input
        if(length(overlap_with_include_list) == 0){
          called_pathogens_significant_filtered <- NULL
          called_pathogens_significant_species_filtered <- NULL
          called_pathogens_significant_genus_filtered <- NULL            
        }
        
        # keep the significant species
        keep_call_sp <- c()
        keep_call_gen <- c()
        for(incl in overlap_with_include_list){
          print(incl)
          for(called in called_pathogens_significant_species){
            print(called)
            if(grepl(incl, called, fixed = TRUE)){
              keep_call_sp <- c(keep_call_sp, called)
              keep_call_gen <- c(keep_call_gen, strsplit(called, " ")[[1]][1])
              call_was_attempted <- TRUE
              text_color = "deepskyblue2"
            }
          }
        }
        called_pathogens_significant_genus_filtered <- keep_call_gen
        called_pathogens_significant_species_filtered <- keep_call_sp         
        
        # calculate mass of called organism
        organism_mass <- 0
        if(length(called_pathogens_significant_species_filtered) > 0){
          organism_mass_list <- ((called_pathogens_significant[called_pathogens_significant$name %in% called_pathogens_significant_species_filtered, c("nt_count")] * overview[overview$sample_name == SN, c("compression_ratio")]) / overview[overview$sample_name == SN, c("total_ercc_reads")]) * 25
          organism_mass <- sum(organism_mass_list)
          print("organism_mass")
          print(organism_mass)
        }
        
      }
      
      
      print("called species before exclude list filtering")
      print(called_pathogens_significant_species)
      
      # # compute metrics - specific to EARLI study
      blood_correct_sp <- sum(unlist(lapply(called_pathogens_significant_species_filtered, function(x){return(grepl(x, blood_known_organisms))}))) >= 1
      blood_correct_genera <- sum(unlist(lapply(called_pathogens_significant_genus_filtered, function(x){return(grepl(x, blood_known_organisms))}))) >= 1
      some_correct_sp <- sum(unlist(lapply(called_pathogens_significant_species_filtered, function(x){return(grepl(x, all_known_organisms_list))}))) >= 1
      some_correct_genera <- sum(unlist(lapply(called_pathogens_significant_genus_filtered, function(x){return(grepl(x, all_known_organisms_list))}))) >= 1
      some_present_sp <- sum(unlist(lapply(sample1_subset$name, function(x){return(grepl(x, all_known_organisms_list))}))) >= 1
      some_present_genera <- sum(unlist(lapply(sample1_subset$genus_name, function(x){return(grepl(x, all_known_organisms_list))}))) >= 1
      print("barcode now...")
      print(barcode)
      result_metrics[[SN]] <- list(SN, barcode, md$FullGroup, call_was_attempted, paste(called_pathogens_significant_species, collapse=';'), paste(called_pathogens_significant_species_filtered, collapse=';'),
                                   blood_correct_sp, blood_correct_genera, some_correct_sp, some_correct_genera,
                                   some_present_sp, some_present_genera, organism_mass)#, paste(all_known_organisms_list, collapse = ';'))


      par(mar=c(1,1,1,1))
      title_text <- paste("total mass: ", round(mass,3), "\nmicrobe mass: ",round(microbe_mass,3),"\ngroup: ",group,"\norganism:",organism)
      x <- barplot(log(sample1_subset$nt_rpm+1),
                   cex.main=.6, xlim = c(0,50), col = result, horiz=TRUE)#, names = sample1_subset$name, las=1, cex.names=.6)
      abline(v=log(1 + 1), col='grey', lty=3)
      text(1, 0, "*minimum rpm threshold", cex=.5, pos=4, col = 'grey')
      title(paste(SN, '\n', metadata[metadata$MICROBE_Plasma_DNA.Seq_filename == SN, c("ID")]), line = -1, cex.main = .8)
      text(log(sample1_subset$nt_rpm+1), x,labels=sample1_subset$name, las=1, srt = 0, cex = .6, col = text_color, pos=4)
      text(30, length(sample1_subset$nt_rpm)-1, paste(title_text, "\n\n",all_organisms), cex=.7, pos=4, col = 'grey')
      if(text_color %in% c("black", "deepskyblue2")){
        text(30,2,paste("called: ",paste(called_pathogens_significant_species,collapse=";"),collapse=":"), cex=.7, col = c("black","brown1")[as.numeric(some_correct_sp) + 1])
      }

      
    }
    
    
    
  }
  dev.off()
  
  
  results_df <- do.call(rbind, result_metrics)
  
  A<-meta_overview[,c("FullGroup", "microbial_mass","initial_input_mass_ng")]
  A$mm_thresh <- A$microbial_mass <= microbial_mass_threshold
  A$tot_thresh <- A$initial_input_mass_ng <= total_mass_threshold
  unlist(lapply(unique(A$FullGroup), function(x){t <- table(A[A$FullGroup == c(x),"mm_thresh"]); return(t["FALSE"]/sum(t))}))
  unlist(lapply(unique(A$FullGroup), function(x){t <- table(A[A$FullGroup == c(x),"tot_thresh"]); return(t["FALSE"]/sum(t))}))
  
  
  # ### PLOT THE RESULTS AND GATHER METRICS
  # 
  colnames(results_df) <- c( "sample_name", "barcode_name", "FullGroup","call_made","organisms","organisms_filtered","blood_correct_sp","blood_correct_genus","some_correct_sp","some_correct_genus","some_present_sp","some_present_genus", "organism_mass")
  results_df <- as.data.frame(results_df)
  # 
  results_df_output <- apply(results_df,2,as.character)
  write.csv(results_df_output, paste(outdir,"pathogen_calling_results.csv", sep=''))
  # 
  colnames(results_df) <- c( "SN","sample_name","barcode_name","FullGroup","call_made","organisms","blood_correct_sp","blood_correct_genus","some_correct_sp","some_correct_genus","some_present_sp","some_present_genus", "organism_mass")
  
  
  # from the significat taxa, identify viral hits by the following criteria: 
  # 1. category == virus
  # 2. nt_rpm > 0.1
  sig_microbe_reports_bgc %>% 
    filter(category == "viruses") %>% 
    filter(nt_rpm > .1) -> virus_hits
  write.csv(virus_hits[,c("sample_name","tax_id","name","nt_rpm","nt_count")], paste(outdir, "virus_hits.csv", sep=''), quote=FALSE)

  
  meta_overview[,c("sample_name","Blood","Lungs","Urine","Stool","Other")]
  
  write.csv(meta_overview[,c("sample_name","Blood","Lungs","Urine","Stool","Other")], paste(outdir, "metadata_to_append.csv", sep=''))
  
  A <- results_df_output[order(results_df_output[,"sample_name"]),]
  B <- meta_overview[order(meta_overview[,"sample_name"]),][,c("sample_name","Blood","Lungs","Urine","Stool","Other","initial_input_mass_ng","microbial_mass","EARLIStudyId")]
  C <- merge(A, B, by = "sample_name")
  write.csv(C, paste(outdir, "merged_pathogen_calling_output.csv", sep=''))
  
  return(C)
  
}


microbe_results <- run_microbe_analysis("./outputs/")
